### PR TITLE
🚩 Milestone 3: Processing data in models | feature/validationsAndTests

### PR DESCRIPTION
**Pull request by Ruthmy**
### Hi there! Ruthmy here. 👋

This is the PR for the [Validations and model specs](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/blog_app_validations_model_spec.md) milestone project. The goal of this milestone is to add validations to the models and write tests for the models.

### Here is a summary of what has been done:

- [x] Updated the migration files to add default values to the counters.
- [x] Updated the `schema.rb` file to match the new migration files.
- [x] Installed the `rspec-rails` gem to create tests for the models using RSpec.
- [x] Created the following tests in order to validate the models and their methods:
  - [x] `user_spec.rb` in `spec/models` to test the `User` model.
  - [x] `post_spec.rb` in `spec/models` to test the `Post` model.
  - [x] `comment_spec.rb` in `spec/models` to test the `Comment` model.
  - [x] `like_spec.rb` in `spec/models` to test the `Like` model.

---

### Thank you for taking the time to review this PR ⭐!

---

### CODE REVIEW

**Comment by prolajumokeoni** [comment]
Hi @Ruthmy, please can you remove the demo section from your readme? It would be nice to also add the table of content lists to your readme 👍🏿

**Comment by Ruthmy** [comment]
Hi @prolajumokeoni 
Yes, of course, I will do the changes as soon as possible.

**Review by prolajumokeoni — APPROVED** [review]
Hi @Ruthmy 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
✔️ added validations 
✔️  wrote unit tests for all the models

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Ruthmy** [comment]
Thank you very much @prolajumokeoni !! ✨ 
Have a nice weekend 😃

**Pull request merged**
